image: node:10.13.0

stages:
  - build
  - test
  - deploy

heroku-deployment:
  stage: deploy
  script:
    - git log
    - npm install --production
    - (echo "machine git.heroku.com"; echo "  login gaurav.katara@sapient.com"; echo "  password $HEROKU_PASSWORD") > ~/.netrc
    - git push https://git.heroku.com/hello-express-10110000.git HEAD:master
